rpc:
  url: "http://localhost:9944"

setup:
  erc20_contract:
    v0: contracts/v0/ERC20.json

  erc721_contract:
    v0: contracts/v0/ERC721.json

  account_contract:
    v0: contracts/v0/OpenzeppelinAccount.json

  fee_token_address: "0x049d36570d4e46f48e99674bd3fcc84644ddd6b96f7c741b1562b82f9e004dc7"
  num_accounts: 1
  chain_id: "MADARA"

run:
  concurrency: 5
  shooters:
    - name: "transfer"
      shoot: 5000
    - name: "mint"
      shoot: 5000
  read_benches:
    - name: "Get Events"
      num_requests: 100
      method: "starknet_getEvents"
      parameters_location: "config/read_params/get_events.json"

report:
  num_blocks: 4
  output_location: "report"

deployer:
  salt: "1"
  address: "0x0000000000000000000000000000000000000000000000000000000000000004"
  signing_key: "0x00c1cf1490de1352865301bb8705143f3ef938f97fdf892f1090dcb5ac7bcd1d"
  legacy_account: false
