rpc:
  url: "http://127.0.0.1:9944"

setup:
  erc20_contract:
    v0: contracts/v0/ERC20.json

  erc721_contract:
    v0: contracts/v0/ERC721.json

  account_contract:
    v0: contracts/v0/OpenzeppelinAccount.json

  fee_token_address: "0x049d36570d4e46f48e99674bd3fcc84644ddd6b96f7c741b1562b82f9e004dc7"
  chain_id: "MADARA_DEVNET"

run:
  concurrency: 5
  shooters:
    - name: "transfer"
      shoot: 10000
    - name: "mint"
      shoot: 10000
  read_benches:
    - name: "Get Events"
      num_requests: 100
      method: "starknet_getEvents"
      parameters_location: "config/read_params/get_events.json"

report:
  num_blocks: 4
  output_location: "report"

deployer:
  salt: "0x42"
  address: "0x067e6d6a380e8b79aeb9d5164643174b3a9e4f381e5f28929441e17b81056f91"
  signing_key: "0x04189668c9e4825137bf31e02d7f6b70120e0d18a16ed9fa73632e8066975065"
  legacy_account: false
