rpc:
  url: "http://127.0.0.1:9944"

setup:
  erc20_contract:
    v0: contracts/v0/ERC20.json

  erc721_contract:
    v0: contracts/v0/ERC721.json

  account_contract:
    v0: contracts/v0/OpenzeppelinAccount.json

  fee_token_address: "0x049d36570d4e46f48e99674bd3fcc84644ddd6b96f7c741b1562b82f9e004dc7"
  num_accounts: 1
  chain_id: "MADARA_DEVNET"

run:
  concurrency: 5
  shooters:
    - name: "transfer"
      shoot: 5000
    - name: "mint"
      shoot: 5000
  read_benches:
    - name: "Get Events"
      num_requests: 100
      method: "starknet_getEvents"
      parameters_location: "config/read_params/get_events.json"

report:
  num_blocks: 4
  output_location: "report"

deployer:
  salt: "0x1"
  address: "0x4a2b383d808b7285cc98b2309f974f5111633c84fd82c9375c118485d2d57ba"
  signing_key: "0x7a9779748888c95d96bbbce041b5109c6ffc0c4f30561c0170384a5922d9e91"
  legacy_account: false
