rpc:
  url: "http://localhost:5050"

setup:
  erc20_contract:
    v0: contracts/v0/ERC20.json

  erc721_contract:
    v0: contracts/v0/ERC721.json

  account_contract:
    v0: contracts/v0/OpenzeppelinAccount.json

  fee_token_address: "0x049d36570d4e46f48e99674bd3fcc84644ddd6b96f7c741b1562b82f9e004dc7"
  num_accounts: 3
  chain_id: "KATANA"

run:
  concurrency: 5
  shooters:
    - name: "transfer"
      shoot: 300
    - name: "mint"
      shoot: 300
  read_benches:
    - name: "Get Events"
      num_requests: 100
      method: "starknet_getEvents"
      parameters_location: "config/read_params/get_events.json"

report:
  num_blocks: 4
  output_location: "report"

deployer:
  salt: "1"
  address: "0x517ececd29116499f4a1b64b094da79ba08dfd54a3edaa316134c41f8160973"
  signing_key: "0x1800000000300000180000000000030000000000003006001800006600"
  legacy_account: true
