rpc:
  url: "https://sharingan.madara.wtf"

setup:
  erc20_contract:
    v0: contracts/v0/ERC20.json

  erc721_contract:
    v0: contracts/v0/ERC721.json

  account_contract:
    v0: contracts/v0/OpenzeppelinAccount.json

  fee_token_address: "0x049d36570d4e46f48e99674bd3fcc84644ddd6b96f7c741b1562b82f9e004dc7"
  num_accounts: 3
  chain_id: "SN_GOERLI"

run:
  concurrency: 5
  shooters:
    - name: "transfer"
      shoot: 1200
    - name: "mint"
      shoot: 1200
  read_benches:
    - name: "Get Events"
      num_requests: 100
      method: "starknet_getEvents"
      parameters_location: "config/read_params/get_events.json"

report:
  num_blocks: 4
  output_location: "report"

# need to add an adress and signing key on sharingan network
deployer:
  address: "0x0000000000000000000000000000000000000000000000000000000000000001"
  signing_key: "0x0"
  salt: "1"
